name: Release on Push

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Create ZIP
        run: |
          zip -r FS25_Better_Time_Control.zip . -x ".git/*" -x ".github/*" -x ".README.md"

      - name: Create or Update Release
        uses: ncipollo/release-action@v1
        with:
          tag: 'latest'
          name: 'FS25_Better_Time_Control'
          artifacts: FS25_Better_Time_Control.zip
          allowUpdates: true
          artifactErrorsFailBuild: true
